const fs = require('fs');
const findConfig = require('find-config');

const dotenvPath = findConfig('.env');

/**
 * Create a new dotenv file.
 */
module.exports = (keyValuePairs) => {
  if (!dotenvPath) {
    throw new Error('Could not find .env file!');
  }

  const fileContents = Object.keys(keyValuePairs)
    .map((key) => {
      const value = keyValuePairs[key];
      return `${key}=${value}`;
    })
    .reduce((a, b) => `${a}\n${b}`, '# generated by pgsh\n');

  fs.writeFileSync(dotenvPath, fileContents);
};
