const fs = require('fs');
const path = require('path');
const findConfig = require('find-config');

const findProjectRoot = require('../util/find-project-root');

/**
 * Create a new dotenv file.
 */
module.exports = (keyValuePairs, encoding = 'utf8') => {
  if (findConfig('.env')) {
    throw new Error('.env file already exists!');
  }

  const fileContents = Object.keys(keyValuePairs)
    .map((key) => {
      const value = keyValuePairs[key];
      return `${key}=${value}`;
    })
    .reduce((a, b) => `${a}\n${b}`, '# generated by pgsh\n');

  const createdPath = path.join(
    findProjectRoot(),
    '.env',
  );

  fs.writeFileSync(
    createdPath,
    fileContents,
    { encoding },
  );

  return createdPath;
};
