const fs = require('fs');
const path = require('path');
const findConfig = require('find-config');

const stringify = require('./stringify');
const findProjectRoot = require('../util/find-project-root');

/**
 * Create a new dotenv file.
 */
module.exports = (keyValuePairs, encoding = 'utf8') => {
  if (findConfig('.env')) {
    throw new Error('.env file already exists!');
  }

  const createdPath = path.join(
    findProjectRoot(),
    '.env',
  );

  fs.writeFileSync(
    createdPath,
    `# generated by pgsh\n\n${stringify(keyValuePairs)}\n`,
    { encoding },
  );

  return createdPath;
};
